plugins { id 'com.android.application' }

android {
    namespace 'ru.pivnoysovet.app'
    compileSdk 34
    defaultConfig {
        applicationId 'ru.pivnoysovet.app'
        minSdk 24
        targetSdk 34
        versionCode 4
        versionName '1.3'
    }
    signingConfigs {
        home {
            storeFile rootProject.file('pivnoysovet.keystore')
            storePassword 'pivnoysovet'
            keyAlias 'pivnoysovet'
            keyPassword 'pivnoysovet'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.home
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.home
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
